### ISSUE TITLE
Version 0.6.2 on composer

### ISSUE THREAD

**Issue by sylven** [paquettg/leaguewrap#102]
I'm new at using composer and I got the paquettg/leaguewrap package but it downloads the version 0.6.2 which still has the old matchhistory class (it has been updated to matchlist 1 month ago).

How can I get version 0.6.3 to work?

**Comment by danijoo** [comment]
What does your composer file look like?

Silviu Chirvasa <notifications@github.com> schrieb am So., 22. Nov. 2015
13:48:

**Comment by sylven** [comment]
I tried using both procedures:
1. Using: composer require paquettg/leaguewrap
2. Using composer.json from the repository:
{
    "name": "paquettg/leaguewrap",
    "type": "library",
    "description": "A wrapper for the League of Legends API.",
    "version": "0.6.2",
    "keywords": ["League", "legends", "wrap", "api", "facade", "proxy"],
    "homepage": "https://github.com/paquettg/leaguewrap",
    "license": "MIT",
    "authors": [
        {
            "name": "Gilles Paquette",
            "email": "paquettg@gmail.com",
            "homepage": "http://gillespaquette.ca"
        }
    ],
    "require": {
        "php": ">=5.5",
        "guzzlehttp/guzzle": "~6.1.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.8.0",
        "mockery/mockery": "~0.9.0",
        "satooshi/php-coveralls": "~0.6.0"
    },
    "autoload": {
        "psr-0": { 
        	"LeagueWrap": "src/"
       	}
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by danijoo** [comment]
Explaining how composer works is a bit out of scope of this board. Please ask at their support forum if you need help on setting up composer.

You only need to create a very basic composer file and add Leaguewrap to it (with the version code you want to have)

**Comment by sylven** [comment]
My bad, I was trying to get version 0.6.3 but it's called dev-master.
Thank you!
