### ISSUE TITLE
Can't get info from a match

### ISSUE THREAD

**Issue by sylven** [paquettg/leaguewrap#105]
I use this code in order to get info about a match (I'm following code from the Readme):
```php
require_once __DIR__.'/vendor/autoload.php';
use LeagueWrap\Api;
$myKey = 'XXXXX';
$api = new Api($myKey);
$api->setRegion('na');
$matchapi = $api->match();
$match = $matchapi->match(2068388618);
```

But it gives me this error:

Catchable fatal error: Argument 1 passed to LeagueWrap\Dto\Match::__construct() must be of the type array, null given, called in /home/.../vendor/paquettg/leaguewrap/src/LeagueWrap/Api/Match.php on line 60 and defined in /home/.../vendor/paquettg/leaguewrap/src/LeagueWrap/Dto/Match.php on line 18

**Comment by danijoo** [comment]
this code works perfectly for me.
