### ISSUE TITLE
Static Data Region

### ISSUE THREAD

**Issue by Nebs987** [paquettg/leaguewrap#109]
In the Region.php file the getStaticDataDomain function is returning the wrong url. It is not adding the region to the end of the url. For example the url that is returned is https://global.api.pvp.net/api/lol/static-data/ but it should be https://global.api.pvp.net/api/lol/static-data/na/ for na.

**Comment by romanzipp** [comment]
Resolved by:

Api/Region.php line 48
```php
protected $defaultStaticDomain = 'https://global.api.pvp.net/api/lol/static-data/';
```
to
```php
protected $defaultStaticDomain = 'https://global.api.pvp.net/api/lol/static-data/%s/';
```
Api/Region.php line 94
```php
return $this->defaultStaticDomain;
```
to
```php
return sprintf($this->defaultStaticDomain, $this->getRegion());
```
