### ISSUE TITLE
Composer require still 0.6.2

### ISSUE THREAD

**Issue by Colorfulstan** [paquettg/leaguewrap#110]
New Version (0.6.4) with matchList is not on composer.

**Comment by danijoo** [comment]
You can replace the version number with 'dev-master' to get the latest
version. But you are right.
I will leave this ticket open for @paquettg to update packegist.

**Comment by Colorfulstan** [comment]
dev-master version doesn't seem to work for me.
Getting errors when executing on XAMPP local Server (worked fine with 0.6.2)

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in [...]\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 [...]\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 [...]\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 [...]\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 [...]\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

Process finished with exit code 255

**Comment by danijoo** [comment]
Is this still happening? I also see this issue from time to time, but usually only if the corresponding api endpoint is down. (Im using dev-master in my production environment fine). It looks like your guzzle somehow fails to verify the ssl connection to riot server.

**Comment by Colorfulstan** [comment]
Still happening, running in a local XAMPP environment with default plugins.
```
phpinfo()
PHP Version => 5.6.8
...
Loaded plugins => mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password
...
```

**Comment by danijoo** [comment]
I have no idea whats wrong. Sorry. 

Im using dev-master without any problems. We updated the used guzzle library from 4.x to 6.x after 0.6.2. Maybe this is the reason why its working for you with the dev-master version. 
Since guzzle is throwing that error for you, it might be worth checking If there is some dependency missing for guzzle library. 

If all else fails, you can also write your own ```LeagueWrap\ClientInterface``` implementation with a client implementation that ignores ssl.

**Comment by Inve1951** [comment]
i had the same issue when i got started with my project
i sloved it by placing the crt file from https://github.com/bagder/ca-bundle into php's directory and setting this line in php.ini:
openssl.cafile="full/path/to/ca-bundle.crt"

hope it helps
(even made an acc to tell you)

**Comment by Colorfulstan** [comment]
@Inve1951 Ill try that somewhen soon and give feedback if it worked for me too. Thanks for sharing anyways :)

**Comment by Colorfulstan** [comment]
@Inve1951 works perfectly, thank you very much!
@danijoo should we change the title for this issue and close it + open a new one regarding the composer version? Got a bit of track here but should be helpful if someone else encounters this problem.

**Comment by danijoo** [comment]
@Colorfulstan I think thats a good idea :+1:
