### ISSUE TITLE
Summoner API change - 403 Forbidden if request by Summoner-Id

### ISSUE THREAD

**Issue by alabama** [paquettg/leaguewrap#112]
Riot removed the request by Id from the Summoner API. Seen here: https://developer.riotgames.com/api/methods#!/1072

They will release a new version (v2.2) which will replace the current one.

At the moment the very first example will not work if you call 
`$bakasan = $summoner->info(74602);      // same thing as above, just to show that an id will work`

**Comment by danijoo** [comment]
Thanks for the notice. I missed that update. I wont have time to make the changes this week because Im moving right now.
Pull request are welcome :)

**Comment by danijoo** [comment]
The endpoint is back up, so Leaguewrap should work again too.

**Comment by alabama** [comment]
Yep true, Riot changed it back again ... yesterday there was even the v2.2 in the endpoint list -.-
