### ISSUE TITLE
[Proposal] StaticData needs region in Request

### ISSUE THREAD

**Issue by alabama** [paquettg/leaguewrap#120]
Hey,

i realized i got some 403 errors, when requesting the Staticdata. Seems like a change in the API : https://developer.riotgames.com/api/methods#!/1055

I would recommend a  change in the Region.php

```
protected $defaultStaticDomain = 'https://global.api.pvp.net/api/lol/static-data/%s/';
...
public function getStaticDataDomain()
{
		return sprintf($this->defaultStaticDomain, $this->getRegion());
}
```

**Comment by alabama** [comment]
The testcase for the RegionTest.php should then look like this:

```
public function testGetDomainStaticData()
{
	$region = new Region('na');
	$this->assertEquals('https://global.api.pvp.net/api/lol/static-data/na/', $region->getStaticDataDomain());
}
```

**Comment by danijoo** [comment]
Seems like you already made a solution. Pull requests are welcome :)

Eugen <notifications@github.com> schrieb am Fr., 9. Sep. 2016, 19:43:

**Comment by alabama** [comment]
should be ready for merging
