### ISSUE TITLE
GetChampion query taking too much time

### ISSUE THREAD

**Issue by musaghauri** [paquettg/leaguewrap#123]
$api->staticData()->getChampion($item['championId'],'tags')->raw()['tags'][0];
The above call is used to getchapion's first tag!
This query is unexpectedly taking 5 to 6 seconds for each champion! 
Can you suggest me a way or any other function to reduce the time! 
This is making me tak 5 to 6 minutes for a player who has 40+ champions!

**Comment by danijoo** [comment]
The lib can't do much on how long network request take. This depends only
on your network and the status of riots api.

Right now you are doing one separate network request per champion. I
suggest you do one request to fetch the data of all champions together once
and then cache that somewhere and reuse it.

Muhammad Musa <notifications@github.com> schrieb am Do., 20. Okt. 2016,
09:58:

**Comment by musaghauri** [comment]
Thanks for your reply! Amazing approach! Worked like a charm! :)
