### ISSUE TITLE
[Summoner Rank] How to get the rank of summoner?

### ISSUE THREAD

**Issue by musaghauri** [paquettg/leaguewrap#124]
How to get the summoner's rank like is he gold silver or bronze?
Because I can't find it in any api call and especially not in summoner's info!

**Comment by danijoo** [comment]
It's in the league endpoint

**Comment by musaghauri** [comment]
done!

**Comment by danijoo** [comment]
Please see https://developer.riotgames.com/api/methods for a reference of
what every endpoint returns. The method you are looking for is the league
endpoint.

Muhammad Musa <notifications@github.com> schrieb am So., 23. Okt. 2016,
13:38:
