### ISSUE TITLE
Annotation Exception with Symfony 2.7

### ISSUE THREAD

**Issue by Kaz-** [paquettg/leaguewrap#126]
Hello ! I tried to use your module in Symfony 2.7 running on PHP 7.0.8 but I get a weird exception about the @chainable annotation. 

`"Doctrine\Common\Annotations\AnnotationException"`
`"[Semantical Error] The annotation "@chainable" in method LeagueWrap\Dto\AbstractDto::set() was never imported. Did you maybe forget to add a "use" statement for this annotation?"
`

Do you have any idea of how i could solve this ?

**Comment by m1so** [comment]
This package isn't tied to Symfony or Doctrine in any way, there is no use of `@chainable` in the whole code base, so there is probably something wrong at your end. We can't help you if you don't provide any code samples.

**Comment by Kaz-** [comment]
Hmm I was using 0.6.2, they were some `@chainable` in AbstractDto , now I got the same issue with `@recursive`  but i just removed it and the problem is gone.

It's just documentation annotation after all ? Isn't it ?

**Comment by m1so** [comment]
That's an old release, `@recursive` is still present in the newer ones for some reason... Also this repository is no longer maintained, consider switching to https://github.com/LeaguePHP/LeagueWrap

**Comment by m1so** [comment]
I pushed a new release (0.7.1) for you on [Packagist](https://packagist.org/packages/league-php/leaguewrap)

**Comment by Kaz-** [comment]
@m1so Thanks a lot :) !
