### ISSUE TITLE
Composer Instalation

### ISSUE THREAD

**Issue by ddrjm** [paquettg/leaguewrap#54]
Hey there.
Not sure if this is a issue but I'm having trouble getting your api to work.
I've installed composer, set it globally and I have also downloaded the repo to my project folder leaving me with just src/LeagueWrap and the rest of the repo.
after I run "composer install" on the repo I get the inteded vendors folder. When I create a simple index.php with the code you provided in the repo main page. I get an error saying "Fatal error: Class 'Api' not found". Could you please provide some insight to what i'm doing wrong? I'm quite new to composer and dependency management in general.

**Comment by danijoo** [comment]
This seems to be more of a composer issue.
You must specify the autoloader in order to use it. Can you please post the exact code you used?
