### ISSUE TITLE
[Request] Add featured games endpoint

### ISSUE THREAD

**Issue by danijoo** [paquettg/leaguewrap#56]
There is a new endpoint to receive featured games:
https://developer.riotgames.com/discussion/riot-games-api/show/ji66sYEN

**Comment by paquettg** [comment]
I added the first steps for this but the api keep returning a 503 error and there does not seem to be a way to specify which region you want the featured games to come from.

https://github.com/paquettg/leaguewrap/commit/b0d411055dbf9d4ffef1e81341abdf2c76f21d95

**Comment by danijoo** [comment]
the 2 new endpoints seem to be down sinze saturday :/
