### ISSUE TITLE
Add Exceptions for common error responses

### ISSUE THREAD

**Issue by danijoo** [paquettg/leaguewrap#59]
What do you think about adding Exceptions for common responses (like 404->NotFoundException, 503->ApiDownException). The current exceptions from guzzle are kinda ugly and the ExceptionClass also depends on the used client what is bad for modularity.

Since this brakes compatibility, we should put it into a new version if you like the idea at all.

**Comment by scolandrea** [comment]
When you think this will be ready?

**Comment by danijoo** [comment]
When somebody wrote it :) 
I want to first hear what paquettg thinks about it before I write something that breaks compatibility of his api.

**Comment by scolandrea** [comment]
You're right!

Tell me if you need help writing it!

:)

**Comment by paquettg** [comment]
I agree that this is probably the best way to go about handling http errors.... I initially did not implement it this way thinking that developers could just program the code to catch the guzzle exceptions but this add in the extra learning of what guzzle throws and how to read it.

This, though, would be backward incompatible so it will require a major number bump, which is not a big deal, just noting. 

also, @scolandrea, if you wish to work on this you are more than welcomed to. I'll probably work on it this weekend but I make no guarantees. If you do though, make sure to add in tests :)

**Comment by danijoo** [comment]
I might work on it as well. Im just not sure what would be a good way to implement it. Right now the clients request function only returns string. It would need to somehow also return response codes so apis can throw the correct error.
Making the Client(Interface) throw the error on its own isnt really an option because Response codes can mean something different for different endpoints (for example Spectator service atm returns a 500 if the summoner is in queue/loading screen while a 500 on any other endpoint would mean that the api is just down)

**Comment by scolandrea** [comment]
Maybe we need to make a difference exception for each Api class. I think this will solve the problem because each endpoint have his own error codes.

**Comment by MrXXIV** [comment]
Yea, my own idea was to have the Client or Api class offer response codes automatically when requested, whether it'd be 200 or 503.

    $api->getResponse()->code;

Have the ability to disable the errors Guzzle or Symphony offers us by catching it ourselves completely.That way, all we need are the codes to write our own redirects like "Summoner Not Found", so that regular users won't be confused or catch a bug on our sites, which will be a major issue for those who are just plain evil.

**Comment by danijoo** [comment]
I thought about changing the Client(Interface) so that it does not return a string, but a custom object containing the response and the status code. The endpoint api class can then decide what exception class is appropriate for the given response code. Maybe with some "defaults" defined in AbstractApi class.

**Comment by paquettg** [comment]
The response object has a toString method so that is does not break any of the existing code that believes that it is a string. It's not the entire feature but it's step one.

**Comment by paquettg** [comment]
I am going to close this issue so we can keep all of the conversation about catching error exceptions in the following issue (don't want to have to look into multiple locations)
https://github.com/paquettg/leaguewrap/issues/69
