### ISSUE TITLE
CurrentGame if player is not in game

### ISSUE THREAD

**Issue by JohnyGemityg** [paquettg/leaguewrap#65]
Hello,

Could someone please help me?¨
I would like to check that summoner is in game.

I call $curGame = $this->api->currentGame()->currentGame($this->player);
$this->api is instance of \LeagueWrap\Api

I tried even

try{
            $curGame = $this->api->currentGame()->currentGame($this->player);
            if($curGame instanceof \LeagueWrap\Dto\CurrentGame)
                return true;
        } catch (Exception $ex) {
            return false;
        }

But if the summoner is not in the game I recive this error:

Catchable fatal error: Argument 1 passed to LeagueWrap\Dto\CurrentGame::__construct() must be of the type array, null given, called in /data/web/virtuals/53877/virtual/www/domains/kafe.popex.eu/vendor/paquettg/leaguewrap/src/LeagueWrap/Api/Currentgame.php on line 66 and defined in /data/web/virtuals/53877/virtual/www/domains/kafe.popex.eu/vendor/paquettg/leaguewrap/src/LeagueWrap/Dto/CurrentGame.php on line 11

Thank you :)

**Comment by Tastefull** [comment]
A quick fix for this is to change Client.php line 70 where it sais 

'exceptions' = false
'exceptions' = true

This way it yields the "old" 404 errors

Note to paquettg: "New Response" is configured with 2 parameters, but the construct only takes one. So the $code is never set. Either only pass $content to the response object and use setCode afterwards or change Response.php __construct to take both parameters. Don't know the impact throughout the whole code, so i just enable the exceptions as i catch guzzle exception already

**Comment by paquettg** [comment]
I added a new way to handle error codes from riot's api. I aldo added documentation about this in the README.
I'll try to keep all of the conversation on how to handle exceptions in the following issue
https://github.com/paquettg/leaguewrap/issues/69
so i'm closing this one.

thanks :)
