### ISSUE TITLE
Unable to retrieve proper champion data.

### ISSUE THREAD

**Issue by Zachman61** [paquettg/leaguewrap#66]
```        
$champs = $api->champion()->free();
        $champions = array();
        foreach($champs as $champ) {
            $champions[] = $api->champion()->championById($champ->id);
        }
```
The above is my code.
I'm trying to retrieve the information about the free champions, including their names, etc. But I can't seem to figure it out and this throws an error for some reason.

**Comment by paquettg** [comment]
What error is being trown?

**Comment by Zachman61** [comment]
It would list all champions inside of each object.
I've changed my code and made it work, but this issue just may be on me.
