### ISSUE TITLE
Using your api without composer

### ISSUE THREAD

**Issue by Virusscript24** [paquettg/leaguewrap#67]
Is there any way to get started without using composer?

Can manually do what composer does?
Because i cant get it to work :(

I just copypasted your code and it says it doesnt find the class Api.
Do i need to set dependencies somewhere?

As i dont want to get into real detail about php because im mainly developing a little desktop application, it would be much easier if i could just copypaste your directory and write use LeagueWrap at the start of the page...

**Comment by danijoo** [comment]
Setting it up with composer should be pretty easy if you follow the guide and know how composer is working.
Of course you can also just copy the project files into your project and use it without composer. For this, you only need to use another autoloader and point it to the leaguewrap namespace. The project follows the PSR standart and should be compatible to *most* available autoloader solutions.

**Comment by Virusscript24** [comment]
Holy **** im a retard ...

Well, i've managed to get composer installed and your package is also installed. However it still tells me it doesnt find

> Fatal error: Class 'LeagueWrap\Api' not found in E:\Programme\Xampp\htdocs\test.php on line 5

Here's my test.php:

> <?php
> require '../vendor/autoload.php';
> use LeagueWrap\Api;

> $api      = new Api("test");           // Load up the API
> $summoner = $api->summoner();          // Load up the summoner request object.
> $bakasan  = $summoner->info('bakasan');// Get the information about this user.

> //$bakasan = $summoner->info(74602)      // same thing as above, just to show that an id will work

> echo $bakasan->summonerLevel;          // 30
> ?>

Also, the autoloader is in the Xampp/vendor directory and LeagueWrap is not automatically downloaded to the htdocs folder (manually putting it in there doesnt help either).

Now i dont get how i should transfer the whole project to a webserver once its working.

But lets get it working first :)

I just hope i dont sound too noobish ...

**Comment by paquettg** [comment]
The first problem I could see with you approach is, you might not be including the composer autoload.php file to gain access to all the files in the package. As per the instructions for composer, you must include the file `./vendor/autoload.php` before attempting to declare any of the objects in the package. If you installed everything else correctly this should be your only problem at the moment.

On that note, though, as danijoo stated, the package would also work with any other PSR-1 compliant autoloader but the package was designed with composer in mind as it is very easy to set up and use. I also don't have any intention in supporting more than one way for this to be set up unless composer falls our of the main stream and another package manager takes its place. 

I'm closing this issue. If you have any more questions/concerns or this does not solve your current issue, please let us know.

**Comment by paquettg** [comment]
For some reason this reply is not on github so my last comment is a little
out of place.
My first concern is the following statement " LeagueWrap is not
automatically downloaded to the htdocs folder (manually putting it in there
doesnt help either)." What do you mean by this? the leaguewrap api should
be found in './vendor/paquettg/leaguewrap/', or at least, that is where
composer is attempting to locate it.

Did you make sure to run
composer install
and
composer dumpautoload
?

On the second note, about transferring the project to a web server. When
you run composer install the first time, or composer update to update all
the packages, it will generate a composer.lock file that you should commit
to the projects repository. Once you deploy to the production server you
run the command composer install, which, if it finds a composer.lock file,
will only install what it finds in the lock with the correct version of the
code that you tested. This does require internet access though.

Best wishes,
 ~ Gilles Paquette

**Comment by Virusscript24** [comment]
It works now and its easier, too.

btw. ye i deleted my comment because i've noticed that i'd probably sound stupid.

I completely missunderstood how composer works and i've tried to install it on a shared freehoster at first, so i fcked up ...

Sorry for wasting your time :(

**Comment by Virusscript24** [comment]
It works now and its easier, too.

btw. ye i deleted my comment because i've noticed that i'd probably sound stupid.

I completely missunderstood how composer works and i've tried to install it on a shared freehoster at first, so i fcked up ...

Sorry for wasting your time :(

@PeopleWithSameProblem
 - Install composer on Xampp
 - Upload Xampp/vendor & Xampp/src to the freehoster
 - write > require 'vendor/autoload.php'; < at the start of each file you want to use the package in
