### ISSUE TITLE
[Proposal] - Caching none 200 Responses

### ISSUE THREAD

**Issue by alabama** [paquettg/leaguewrap#69]
I had a problem with caching none 200 code responses, mostly with the "currentGame" request. Every Response was cached, even the 503 oder 404 ones, with the amount of seconds i specified.

First there was a forgotten parameter in LeagueWrap\Response Line 26
```php
/**
 * The primary content of the response.
 *
 * @param string $content
 * @param string $code
 */
public function __construct($content, $code)
{
	$this->content = trim($content);
	$this->setCode($code);
}
```

With the given code information i could decide if the response was a valid one and would change the file LeagueWrap\Api\AbstractApi Line 324 - 335
```php
$content = $this->clientRequest($static, $uri, $params);

$cacheContent = true;
//if you got a Response object check if the response code is a valid 200
if($content instanceof Response)
{
	$cacheContent = $content->getCode() === 200;
}

if($cacheContent)
{
	// we want to cache this response
	$this->cache->set($content, $cacheKey, $this->seconds);
}
```

The code above checks if the returned content is a Response object. If it is it will check the setted code for a 200 response and only this ones will be cached.
If the content is not a Resonse object it will be cached without restriction

**Comment by danijoo** [comment]
I agree that error responses shouldnt be cached for some apis. Especially for the current game api and if the api has issues and responds with status code 5xx.
For other apis, caching a 404 is fine though. For example if I check for a player name, and this player does not exist, I dont want to make another api call 1 second later. 

Maybe there should be some kind of additional flag for AbstractApi#request so we can turn caching if errors on/off depending on the used Api class.

**Comment by alabama** [comment]
Totally agree, I didn't think about the request where 404 are fine, like you described.

**Comment by danijoo** [comment]
Im a bit short on time at the moment. If you want to do this, feel free to make a pull request :) Im pretty sure @paquettg also likes this suggestion

**Comment by alabama** [comment]
Ok, created one.

I would suggest something like a cache configurator, where you can determine caching of the different responses. Riot has a this list of responses: https://developer.riotgames.com/docs/response-codes
If think LeagueWrap already handles: 400, 401, 429. 
I can't think of a  logic purpose to cashe 5XX  error codes, so there is only 200 and 404 Left. 

In the cache configurator you would be able to say a 404 response for the currentGame API should be cashed for 1 minute (or not cashed at all) and a 200 response for 15minutes. For the summoner API you could say all responses should be cashed for X seconds. 
What do you think about that?

**Comment by danijoo** [comment]
The way leaguewrap handles exceptions needs a rewrite anyways (see #59 ). At the moment, most of the guzzle exceptions bubble through the api and need to be handled by the user manually.

**Comment by paquettg** [comment]
Ok, I added some code in my most recent push that should handle error codes a lot nicer and with our own exceptions.
I also added documentation for the new exceptions and what to expect.
Let me know what you guys think.

**Comment by alabama** [comment]
Nice Job! I Like the changes!
Only in LeagueWrap\Client code with 'if (is_object($body))' I would change it to 'if ($body instance of StreamInterface)' because guzzle returns a StreamInterface object which has the method: 'seek()' and 'read', but this is only some beautification.

The next step would be the cache configurator ;)

**Comment by paquettg** [comment]
I tried pulling #70 but, with the current changes, that does not work. It was also hard codded and would have been changed in the long run for the more dynamic system. 
We just need to figure out a good way to allow people to set cache time per response code with out it being to hard to use and intrusive to people already using it. Any thoughts would be appriciated.

**Comment by danijoo** [comment]
I think this shoud not be merged until some issues are resolved anyways. You really dont want to have 5xx errors sitting in your cache (and 4xx in some cases).

With the changes to exceptions (which are pretty cool), I think the best default is to not cache 5xx at all and cache 4xx for everything except life games. Maybe a simple **enableExceptionCaching(boolean)** to enable/disable this default behaviour is enough.
