### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by kahl** [paquettg/leaguewrap#74]
I'm trying to test the wrapper with MAMP but this code

<?php

use LeagueWrap\Api;

$api      = new Api($key = 123456); // Load up the API 123456 stands for my real key that I cannot share but in the actual script is right
$summoner = $api->summoner();          // Load up the summoner request object.
$bakasan  = $summoner->info('bakasan') // Get the information about this user.

$bakasan = $summoner->info(74602)      // same thing as above, just to show that an id will work

echo $bakasan->summonerLevel;          // 30
echo $bakasan->id;                     // 74602
echo $bakasan->name;                   // "bakasan"
echo $bakasan->profileIconId;          // 24
echo $bakasan->revisionDate;           // 1387391523000
echo $bakasan->revisionDateStr;        // "12/18/2013 06:32 PM UTC"

?>

But I get "NetworkError: 500 Internal Server Error - http://localhost:8888/leaguewrap-master/tests/test.php"

Any idea?

**Comment by paquettg** [comment]
well, you have a bunch of syntax errors... or at least 2 that I can notice off the top of my head. You are missing the ; after both info calls.

**Comment by kahl** [comment]
Hi man,

I've copied the new readme code
<?php

use LeagueWrap\Api;

$api      = new Api($key = "c84e4023-0042-467f-bf5b-16cc4f700c92"); // Load up the API
$summoner = $api->summoner();           // Load up the summoner request object.
$bakasan  = $summoner->info('bakasan'); // Get the information about this user.

$bakasan = $summoner->info(74602);      // same thing as above, just to show that an id will work

echo $bakasan->summonerLevel;           // 30
echo $bakasan->id;                      // 74602
echo $bakasan->name;                    // "bakasan"
echo $bakasan->profileIconId;           // 24
echo $bakasan->revisionDate;            // 1387391523000
echo $bakasan->revisionDateStr;         // "12/18/2013 06:32 PM UTC"

?>

but you can go here http://70.37.98.151/leaguewrap/tests/test2.php and you will find out that for some reason still doesn't work. . .

**Comment by paquettg** [comment]
I see no output in the link you gave me... is there suppose to be something
there? Like an error or something?

Best wishes,
 ~ Gilles Paquette

**Comment by kahl** [comment]
Hi man,

Thanks for the reply. That's the problem: the page has no output and that happens with all the test pages even the ones you created. If you check the page with firebug firephp extension you discover that the page throws a 500 internal server error. I can give you access to the server if you want to investigate the problem.

Best,
Pasquale

**Comment by danijoo** [comment]
Can you please post the stacktrace?

**Comment by kahl** [comment]
Basically I get this 
Failed to load resource: the server responded with a status of 525 (OK)

**Comment by kahl** [comment]
Please find here http://70.37.98.151/leaguewrap/tests/test2.php the errors exposed

**Comment by danijoo** [comment]
It cannot find the leaguewrap classes. Seems like your project is not setup
correctly. Are you using composer?

**Comment by kahl** [comment]
yep I run sudo composer.phar install and then sudo composer.phar update in leaguewrap folder. . .

**Comment by danijoo** [comment]
Did you put the composer autoloader script on the start of your file?

**Comment by kahl** [comment]
you mean something like this:


<?php

require 'vendor/autoload.php';

use  \LeagueWrap\Api;

$api      = new Api($key = "c84e4023-0042-467f-bf5b-16cc4f700c92"); // Load up the API
$summoner = $api->summoner();           // Load up the summoner request object.
$bakasan  = $summoner->info('bakasan'); // Get the information about this user.

$bakasan = $summoner->info(74602);      // same thing as above, just to show that an id will wo$

echo $bakasan->summonerLevel;           // 30
echo $bakasan->id;                      // 74602
echo $bakasan->name;                    // "bakasan"
echo $bakasan->profileIconId;           // 24
echo $bakasan->revisionDate;            // 1387391523000
echo $bakasan->revisionDateStr;         // "12/18/2013 06:32 PM UTC"

?>

**Comment by danijoo** [comment]
Yes. But this is a bit out of the scope of this repository. For information
about how to set up composer repositories, you should refer to the composer
documentation.

Also, you should not post your api key here.

Regards,
Danijoo

**Comment by kahl** [comment]
Ok thanks guys, maybe it is only a problem of the path. . .

**Comment by kahl** [comment]
At the end of the day it was only a path problem, but I am still not getting the death positions (in x and y coordinates) for a specific summoner passed as variable

<?php

include_once '../vendor/autoload.php';

use  \LeagueWrap\Api;

$api      = new Api($key = "######-######-######"); // Load up the API

if($_GET["summonername"])
{
   $summoner = $api -> summoner();
   $mysummoner = $summoner->info($_GET["summonername"]);
   $summonerid = $mysummoner->id;

   $matchHistory = $api->matchHistory();
   $matches = $matchHistory->history($summonerid);
   $lastmatchid = $matches[0]->matchId;

   $matchapi = $api->match();
   $match = $matchapi->match($lastmatchid, true);
   $timeline = $match->timeline;

   
   echo $summonerid;
   echo $timeline;
}

As you can see here I get the id of the summoner but nothing more http://70.37.98.151/leaguewrap/tests/test2.php?summonername=bakasan
