### ISSUE TITLE
LeagueWrap\Response\Http404 / Resource not found / thrown AbstractApi.php on line 553

### ISSUE THREAD

**Issue by oimel** [paquettg/leaguewrap#75]
Hello,
I know this isn't a support forum, but I hope you will help me nonetheless.
I've never worked with composer before (I'm new to this web thing). So I downloaded and installed wamp and composer. I created the dependencies json file in my project folder and added leaguewrap to it. After that I ran 'php composer.phar install' which worked fine. I also added the requirement for the autoload file to my index.php.
I can search for a summoner and get all the info etc. My problems start when I enter a summoner that doesn't exist. It throws out this error (index.php included): http://pastebin.com/3tFnBYb6

I tried following the examples for http exceptions in the readme, but I can't even add 'catch (LeagueWrap\Response\Http404)' without causing a syntax error.

Can you help me, please?

Thanks in advance.

**Comment by paquettg** [comment]
You need to implemnent a try catch block to catch the exception.

http://php.net/manual/en/language.exceptions.php

You can't just add the catch(...) line, you need to have it follow a try block first. Hopefully the above link will also help you with your problem.

**Comment by oimel** [comment]
Thanks for the quick response. 
I did use try, but catch doesn't work because of "syntax error, unexpected ')', expecting variable (T_VARIABLE)"
http://pastebin.com/R0fPF0jY

**Comment by danijoo** [comment]
Plesse read the posted link carefully. You are missing a variable for your
exception:

catch(Exception $e) {....}

**Comment by oimel** [comment]
Well, that's embarrassing.
It's running now, thank you for your help and time.
