### ISSUE TITLE
League Api don't catch 404

### ISSUE THREAD

**Issue by UnforgivenCL** [paquettg/leaguewrap#78]
Hi , when i'm ussing the League Api (league()) i use it with a try and catch, and they didn't catch the 404 error, it's a code problem of my app or of the API? With the stats() works nice but with league didn't work

**Comment by danijoo** [comment]
Can you please provide some example code?

**Comment by danijoo** [comment]
Seems like you got it fixed yourself since theres no update for 2 months.
