### ISSUE TITLE
Is there any intention of including the new matchlist functionality?

### ISSUE THREAD

**Issue by radean0909** [paquettg/leaguewrap#79]
With the matchlist being implemented and Riot requesting matchhistory be updated by Sept 22 are there plans to include this in the wrapper class?

**Comment by danijoo** [comment]
Yes :) i plan to do that. Im not sure when I find time though.

radean0909 <notifications@github.com> schrieb am So., 26. Juli 2015 06:56:

**Comment by danijoo** [comment]
I added the new endpoint and updated the documentation.
