### ISSUE TITLE
StaticOptimizer error - "typo" with masteries

### ISSUE THREAD

**Issue by Colorfulstan** [paquettg/leaguewrap#81]
`$api->attachStaticData()` produces an Error in `StaticOptimizer.php` if Masteries are involved due to line 80+

```
$method .= 's';
$data    = $staticData->$method();
```

which tries to calls $staticData->getMasterys()
(instead of getMasteries() )

```
if (substr($method, -1) == 'y'){
    $method = substr($method, 0, -1);
    $method .= 'ie';
}
```
fixed that for me for now

**Comment by danijoo** [comment]
A pull request would be nice! :+1:

**Comment by Colorfulstan** [comment]
might be doing that somewhen over the week.
Also seems like $staticdata->getMasteries() and staticdata->getRunes() ain´t working at all in that context anyways :X

**Comment by paquettg** [comment]
Merged pull request related to this issue.
