### ISSUE TITLE
static data for runes and masteries doesn´t get attached to currentGame() result

### ISSUE THREAD

**Issue by Colorfulstan** [paquettg/leaguewrap#83]
```
$api->attachStaticData(true);
$currentGame = $api->currentGame();
print_r($currentGame->currentGame($summonerInfo)->raw());
$api->attachStaticData(false);
```

gives an Array where – regarding the attached static data – only summonerspells and champions are attached, not masteries and runes.
The isolated calls for `$staticdata->getMasteries()` and `$staticdata->getRunes()` deliver the data.
As stated in issue #81 the `getMasteries()` obviously gets called within `StaticOptimizer.php`, but the data doesn´t reach the currentGame() result

**Comment by danijoo** [comment]
This, together with #81 makes me think the whole attach static data thing might broken for runes/masteries. Let me see if I find some time during the week to look into this more closely.

**Comment by paquettg** [comment]
I found the bug. If a DTO contained attached static data it would not allow static data to be attached to any of its children. This has been fixed and I added tests to ensure it does not happen again.
