### ISSUE TITLE
Requesting timeline for match does not return the timeline

### ISSUE THREAD

**Issue by epoch365** [paquettg/leaguewrap#84]
When requesting the match timeline, the timeline is not returned. The issue seems to be in Api\Match.php:53 in the match function where the url query parameter includeTimeline is set to true but in the request the boolean 'true' is translated to '1' which is not recognized by the Riot api. A simple fix is to change line 53 from
```$response = $this->request('match/'.$matchId, ['includeTimeline' => $includeTimeline]);```
to
```$response = $this->request('match/'.$matchId, ['includeTimeline' => 'true']);```

**Comment by danijoo** [comment]
The reason for this is line 68 of LeagueWrap\Client.php where the query params are built using the php method http_build_query() (http://php.net/manual/de/function.http-build-query.php). This method automatically inserts 0 or 1 into the query string for boolean values.
