### ISSUE TITLE
[Request] JSON serialization of objects

### ISSUE THREAD

**Issue by epoch365** [paquettg/leaguewrap#85]
Using json_encode on a DTO object fails to serialize it to JSON. Making the class Dto\AbstractDto implement JsonSerializable could solve this issue with minimal effort for PHP >= 5.4.
* line 7:
```Abstract class AbstractDto implements \JsonSerializable {```
* and implement this function in the class:
```
/**
 * Returns the properties of the object to be serialized to JSON.
 *
 * @return object
*/
public function JsonSerialize()
{
    return $this->info;
}
```
This may require more work than this to ensure proper serialization of all objects.

**Comment by danijoo** [comment]
Theres also $object->raw() which returns the json response as array.

Bryan <notifications@github.com> schrieb am Mo., 31. Aug. 2015 06:51:
